### ISSUE TITLE
No "exports" main defined

### ISSUE THREAD

**Issue by justinwaite** [eratio08/vitest-mock-extended#19]
Upgrading from `0.1.4 -> 0.1.5` causes the following error to occur when running tests:
```
Error: No "exports" main defined in /my-project/node_modules/vitest/package.json
 ❯ Object.<anonymous> node_modules/vitest-mock-extended/lib/CalledWithFn.js:5:18
```

using vitest version `0.15.2`

**Comment by eratio08** [comment]
checking!

**Comment by eratio08** [comment]
@justinwaite I hope that this is now fixed in 0.1.6

**Comment by justinwaite** [comment]
@eratio08 that seems to have done it! Though if I were you I would define a range for the vitest peer dependency instead of a pinned version. 

Thanks!

**Comment by eratio08** [comment]
Will re-add a range. It seemed to be caused by version smaller 0.15.2
