### ISSUE TITLE
Can't mockDeep Prisma client

### ISSUE THREAD

**Issue by smolak** [eratio08/vitest-mock-extended#50]
Hi

When I try to mockDeep Prisma client, I get:

```sh
 ❯ Object.set node_modules/vitest-mock-extended/lib/Mock.js:72:23
TypeError: Cannot set property enabled of #<Object> which has only a getter
     70|     set: (obj, property, value) => {
     71|         // @ts-ignore All of these ignores are due to https://github.com/microsoft/TypeScript/issues/1863
     72|         obj[property] = value;
```

Prisma client is exported from a local module:

```ts
// <root>/prisma/index.ts
import { PrismaClient } from "@prisma/client";

let prisma: PrismaClient;

if (process.env.NODE_ENV === "production") {
  prisma = new PrismaClient({
    errorFormat: "minimal",
  });
} else {
  // @ts-ignore
  globalThis["prisma"] =
    // @ts-ignore
    globalThis["prisma"] ||
    new PrismaClient({
      errorFormat: "pretty",
    });

  // @ts-ignore
  prisma = globalThis["prisma"];
}

export default prisma;
```

Implementation uses it like so:

```ts
// <root>/user/model/index.ts
import prisma from '../../prisma';

// ...
```

Test implementation:
```ts
import { PrismaClient } from "@prisma/client";
import prisma from '../../prisma';
import { mockDeep } from 'vitest-mock-extended';

const prismaMock = mockDeep<PrismaClient>(prisma);

// ...
```

**Comment by smolak** [comment]
Or am I using it wrong?

**Comment by eratio08** [comment]
I never used deep but referring to https://github.com/marchaos/jest-mock-extended#deep-mocks you might not need deep for your case. You already hand in a mock implementation `prisma`. Deep would be used if you do not want to define a mock implementation for all the layers but only want to mock some deeply nested function/prop. I'm not sure how the prisma client works or expects in structure. Does it work if you are using just jest?

**Comment by edwardbrowncross** [comment]
```js
const prismaMock = mockDeep<PrismaClient>(prisma);
```

I'm not sure this line is correct. The parameter `mockDeep` takes is an optional mock implementation - it should not be the real implementation. 

See the [example in the Prisma docks](https://www.prisma.io/docs/guides/testing/unit-testing) where they do this:

```js
const prismaMock = mockDeep<PrismaClient>();
```
(no argument given)

If you were to use that optional parameter as intended it would probably look something more like this:

```js
const prismaMock = mockDeep<PrismaClient>({
  customers: {
    findFirst: () => ({ name: 'Alice McTest' })
  },
});
```

**Comment by smolak** [comment]
Hi.

Actually... I think it's the order of imports and all that made it work, meaning:
 - import the real thing first
 - mock the imported thing (by path)

Here's my `prismaMock` implementation:

```ts
import { PrismaClient } from "@prisma/client";
import { mockDeep, mockReset, DeepMockProxy } from "vitest-mock-extended";

import prisma from "../../prisma";

vi.mock("../../prisma", () => mockDeep<PrismaClient>());

beforeEach(() => {
  mockReset(prismaMock);
});

export const prismaMock = prisma as unknown as DeepMockProxy<PrismaClient>;
```

If this is _correct_ then I assume we can close the issue.

**Comment by eratio08** [comment]
I guess if it works it's correct :)

**Comment by smolak** [comment]
Yes, it does. I will close it then. Thanks for the help everyone.
