### ISSUE TITLE
Using vitest-mock-extended with "NodeNext" typescript config does not compile

### ISSUE THREAD

**Issue by mhintzke** [eratio08/vitest-mock-extended#546]
Without `vitest-mock-extended`: 

https://stackblitz.com/edit/vitest-5820

With `vitest-mock-extended`: 

https://stackblitz.com/edit/vitest-5820-megvgc

![image](https://github.com/user-attachments/assets/756032ea-4983-4a69-91ee-1e0ba93c25d2)

Workaround: 

Use `skipLibCheck: true` in `tsconfig.json`, but this isn't great

Another developer from `vitest` issues showed me this https://arethetypeswrong.github.io/?p=vitest-mock-extended%402.0.0 which shows the packages has malformed module syntax.

**Comment by eratio08** [comment]
@mhintzke thanks for reporting this! I will try to fix this.
