### ISSUE TITLE
Deep mocking results in a TypeScript error + extreme compilation slowness

### ISSUE THREAD

**Issue by gertjangaillet** [eratio08/vitest-mock-extended#59]
I'm experiencing the exact same behavior and error message as described in https://github.com/marchaos/jest-mock-extended/issues/97 when using v0.1.16

v0.1.10 does not yet have the issue. I didn't test with other versions between 0.1.10 and 0.1.16

**Comment by eratio08** [comment]
I need to included the upstream changes, that might fix it. Will try as soon as I find the time!

**Comment by eratio08** [comment]
@gertjangaillet please check it this it resolved in v1.0.0

**Comment by gertjangaillet** [comment]
@eratio08 it looks like there is something wrong (or was there perhaps a breaking change?) with the exports:

```
src/.../....test.ts:2:22 - error TS7016: Could not find a declaration file for module 'vitest-mock-extended'. '/.../node_modules/vitest-mock-extended/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/vitest-mock-extended` if it exists or add a new declaration (.d.ts) file containing `declare module 'vitest-mock-extended';`

2 import { mock } from 'vitest-mock-extended'
                       ~~~~~~~~~~~~~~~~~~~~~~
```

Or am I missing something? Do you have a @types package that I'm not finding?

**Comment by eratio08** [comment]
Looks like I broke the types. Checking!

**Comment by eratio08** [comment]
@gertjangaillet please check v1.0.2

**Comment by gertjangaillet** [comment]
Thanks, that works perfectly!

**Comment by eratio08** [comment]
@gertjangaillet are the performance issues also resolved for you?
