### ISSUE TITLE
Named export 'mockDeep' not found

### ISSUE THREAD

**Issue by epotter24G** [eratio08/vitest-mock-extended#64]
```
SyntaxError: Named export 'mockDeep' not found. The requested module 'vitest-mock-extended' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'vitest-mock-extended';
const { mockDeep } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:533:24)
    at async loadESM (node:internal/process/esm_loader:91:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```
I get this error when importing this:
```js
import { mockDeep, DeepMockProxy } from 'vitest-mock-extended';
```
[Here](https://github.com/epotter24G/vitest-mock-extended-error) is a simple reproduction of the error, you should be able to see it by running `pnpm dev`

**Comment by eratio08** [comment]
Mh looks like something is off with the packaging. It should be an esmodule and not a common js one.

**Comment by eratio08** [comment]
I tried to load the module natively without tsm which seems to work fine. So this seems to be related to the lib not being tsm compliant. Checking now how this can be achieved.

**Comment by eratio08** [comment]
@epotter24G quick question why are you trying to load a transpiled esm module with the `tsm`? I can only imagine that this wont work because it already js and not a ts module

**Comment by epotter24G** [comment]
@eratio08 You can use `tsm` (mostly) like a drop-in replacement to `ts-node`, so it can run js no problem. I also just updated the example repo to show the same thing happening with `ts-node`.

**Comment by epotter24G** [comment]
@eratio08 In my particular use case I'm using a monorepo and have Prisma in a separate project. I want to export a mock of Prisma alongside the real Prisma. I suppose I could work around it by having a second export file, but if I export them in the same `index.ts` it will cause this crash.

**Comment by eratio08** [comment]
trying to fix this in https://github.com/eratio08/vitest-mock-extended/pull/70 should now be a proper esm that node understands. You will see it will now fail in the vitest code parts

**Comment by eratio08** [comment]
Rolled back the mjs packaging as it did cause errors for regular users. I guess this wont be fixed for now. If you want dig into the whole esm mjs topic feel free to prep a PR

**Comment by eratio08** [comment]
@epotter24G this might be fixed with the same steps of https://github.com/eratio08/vitest-mock-extended/issues/158 could revisit this and tell me if it works now

**Comment by eratio08** [comment]
Closing this as there was no response by the OP
