### ISSUE TITLE
Cannot find module '...\lib\esm\Mock' imported from ...\lib\esm\index.mjs

### ISSUE THREAD

**Issue by james-elicx** [eratio08/vitest-mock-extended#69]
Hello,

With version 1.0.4, I receive the following error when I import `mockDeep` from `vitest-mock-extended` in my tests and run them.

```
Error: Cannot find module 'C:\...\node_modules\vitest-mock-extended\lib\esm\Mock' imported from C:\...\node_modules\vitest-mock-extended\lib\esm\index.mjs
```

Changing to version 1.0.3 seems to import the from the library fine when running my tests.

**Comment by eratio08** [comment]
Thanks for reporting! checking

**Comment by james-elicx** [comment]
> @james-elicx Which node version are you using and how are you importing it? I tried on the example project and it seems to work for me.

Hey there, I'm using Node.js v16.15.0

Just pushed a reproduction for you to see.

Version 1.0.4 - https://github.com/james-elicx/prisma-mock/tree/vme/1.0.4
Version 1.0.3 is in use on main.

**Comment by eratio08** [comment]
Let's see if https://github.com/eratio08/vitest-mock-extended/pull/70 will fix this.

**Comment by eratio08** [comment]
@james-elicx please try v1.0.5

**Comment by james-elicx** [comment]
> @james-elicx please try v1.0.5

With v1.0.5, I get the following when I run my tests, which is odd considering it doesn't happen on v1.0.3.

```
Error: Vitest was initialized with native Node instead of Vite Node.

One of the following is possible:
- "vitest" is imported outside of your tests (in that case, use "vitest/node" or import.meta.vitest)
- "vitest" is imported inside "globalSetup" (use "setupFiles", because "globalSetup" runs in a different context)
- Your dependency inside "node_modules" imports "vitest" directly (in that case, inline that dependency, using "deps.inline" config)
- Otherwise, it might be a Vitest bug. Please report it to https://github.com/vitest-dev/vitest/issues
```

Link to branch with v1.0.5 - https://github.com/james-elicx/prisma-mock-vitest/tree/vme/v1.0.5

**Comment by eratio08** [comment]
I guess the whole cjs & esm support seems to be the cause of this. I will roll back that change an just package for esm

**Comment by eratio08** [comment]
@james-elicx should be back to normal again

**Comment by james-elicx** [comment]
> @james-elicx should be back to normal again

I can confirm that it's back to working.

Thank you for the time that you've had to spend on this :)
