### ISSUE TITLE
Types path is wrong in package.json for v1.0.5

### ISSUE THREAD

**Issue by xrnoz** [eratio08/vitest-mock-extended#73]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `vitest-mock-extended@1.0.5` for the project I'm working on.

The types path is wrong in package.json for v1.0.5, this caused VS Code to not load the types for me.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/vitest-mock-extended/package.json b/node_modules/vitest-mock-extended/package.json
index a057f78..18a73a6 100644
--- a/node_modules/vitest-mock-extended/package.json
+++ b/node_modules/vitest-mock-extended/package.json
@@ -9,7 +9,7 @@
     },
     "author": "Eike Lurz <eike.lurz@tuta.io>",
     "license": "MIT",
-    "types": "./lib/cjs/types/index.d.ts",
+    "types": "./lib/cjs/types/types/index.d.ts",
     "main": "./lib/cjs/index.js",
     "files": [
         "lib/**/*"
```

This fixed IntelliSense for me.

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by eratio08** [comment]
Hey thank you for raising! Will fix this asap

**Comment by eratio08** [comment]
should be resolved in https://github.com/eratio08/vitest-mock-extended/commit/931868a43bb69d169554b05a6b9dd036df7766de
